name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Replace with the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build the EXE
      run: |
        pyinstaller --onefile --noconsole NDAConverter.py

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/NDAConverter.exe
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          This is an automated release created by GitHub Actions.
        draft: false
        prerelease: false
